"use client";

import { useState, useTransition } from "react";
import { Bot, BriefcaseBusiness, MessageSquareText, Send, WandSparkles } from "lucide-react";
import { rewriteBullet } from "@/lib/api";
import { RewriteTone } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const tones: { value: RewriteTone; label: string }[] = [
  { value: "fresher", label: "Fresher" },
  { value: "faang", label: "FAANG" },
  { value: "startup", label: "Startup" },
  { value: "senior_engineer", label: "Senior" }
];

export function AiTools() {
  const [bullet, setBullet] = useState("Worked on dashboard and improved API performance.");
  const [tone, setTone] = useState<RewriteTone>("faang");
  const [rewrites, setRewrites] = useState<string[]>([]);
  const [isPending, startTransition] = useTransition();

  return (
    <Tabs defaultValue="rewrite">
      <TabsList>
        <TabsTrigger value="rewrite"><WandSparkles className="mr-2 h-4 w-4" />Rewrite</TabsTrigger>
        <TabsTrigger value="coach"><Bot className="mr-2 h-4 w-4" />Career Coach</TabsTrigger>
        <TabsTrigger value="cover"><BriefcaseBusiness className="mr-2 h-4 w-4" />Cover Letter</TabsTrigger>
      </TabsList>
      <TabsContent value="rewrite">
        <Card>
          <CardHeader>
            <CardTitle>AI Resume Rewrite</CardTitle>
            <CardDescription>Quantified, action-led bullet rewrites across hiring contexts.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Textarea value={bullet} onChange={(event) => setBullet(event.target.value)} />
            <div className="flex flex-wrap gap-2">
              {tones.map((item) => (
                <Button key={item.value} variant={tone === item.value ? "default" : "outline"} size="sm" onClick={() => setTone(item.value)}>
                  {item.label}
                </Button>
              ))}
            </div>
            <Button
              disabled={isPending}
              onClick={() =>
                startTransition(async () => {
                  const response = await rewriteBullet(bullet, tone);
                  setRewrites(response.rewrites);
                })
              }
            >
              <Send className="h-4 w-4" />
              Rewrite Bullet
            </Button>
            <div className="grid gap-3 md:grid-cols-3">
              {rewrites.map((rewrite) => (
                <div key={rewrite} className="rounded-lg border p-4 text-sm text-muted-foreground">
                  {rewrite}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </TabsContent>
      <TabsContent value="coach">
        <Card>
          <CardHeader>
            <CardTitle>Career Assistant</CardTitle>
            <CardDescription>Skill gaps, roadmaps, certification picks, and project ideas are generated by the backend RAG agents.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-3">
            {["Close React system design gaps with SSR, caching, and observability projects.", "Add one production AI feature using RAG, evals, and prompt versioning.", "Target AWS SAA or GCP ACE only if cloud ownership appears in target roles."].map((item) => (
              <div key={item} className="rounded-lg border p-4 text-sm text-muted-foreground">{item}</div>
            ))}
          </CardContent>
        </Card>
      </TabsContent>
      <TabsContent value="cover">
        <Card>
          <CardHeader>
            <CardTitle>Cover Letter Generator</CardTitle>
            <CardDescription>Company-specific letters with resume evidence and role alignment.</CardDescription>
          </CardHeader>
          <CardContent className="flex items-center gap-3 rounded-lg border p-4 text-sm text-muted-foreground">
            <MessageSquareText className="h-5 w-5 text-primary" />
            Generate tailored letters through <code>/api/v1/cover-letter/generate</code> with export-ready markdown.
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  );
}
